# Generated by Django 5.1.1 on 2024-09-20 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, default="default.jpg", upload_to="profile_pics"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMINISTRATOR", "Administrator"), ("USER", "User")],
                        default="USER",
                        max_length=20,
                    ),
                ),
                (
                    "communication_channel",
                    models.CharField(
                        choices=[("POST", "Pošta"), ("EMAIL", "Email")],
                        default="EMAIL",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
