# Generated by Django 5.1.1 on 2024-09-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="profile_pics/default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
