# Generated by Django 5.1.1 on 2024-09-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_product_author_product_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
