# Generated by Django 5.1.1 on 2024-10-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_order_address_order_delivery_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(default="Zadejte adresu doručení", max_length=255),
        ),
    ]
