# Generated by Django 5.1.1 on 2024-10-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_order_delivery_price_alter_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
